# Generated by Django 5.2.10 on 2026-01-16 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='TipoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriagasto')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('periodo', models.CharField(max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='liquidaciones/')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('obra_social_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField()),
                ('monto_paciente', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia/MP')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado (Cobrado)'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('nota_evolucion', models.TextField(blank=True, null=True)),
                ('obra_social_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.obrasocial')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipotratamiento')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copago_sugerido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obrasocial')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipotratamiento')),
            ],
            options={
                'verbose_name_plural': 'Aranceles (Precios)',
                'unique_together': {('obra_social', 'tratamiento')},
            },
        ),
    ]
