# Generated by Django 5.2.10 on 2026-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
