# Generated by Django 5.2.10 on 2026-01-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turno_monto_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
