# Generated by Django 4.2.10 on 2026-01-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gasto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(default='Mi Consultorio', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', '⏳ Pendiente'), ('FINALIZADO', '✅ Atendido'), ('CANCELADO', '🚫 Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
